server:
  port: 8080

ai:
  deepseek:
    base-url: https://api.deepseek.com/v1
  gemini:
    base-url: https://generativelanguage.googleapis.com/v1beta

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
